apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatherplan-client.fullname" . }}
  labels:
    {{- include "gatherplan-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "gatherplan-client.selectorLabels" . | nindent 4 }}
