image:
  repository: "us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-client"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "698b2fcde7dc"


serviceAccount:
  create: false


ingress:
  enabled: true
  hosts:
    - host: test.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
  port: 3000