image:
  repository: us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-client
  pullPolicy: IfNotPresent
  tag: vfdef53c
env:
  - name: API_URL
    value: http://test-api.gatherplan.site
command:
  - /bin/bash
args:
  - '-c'
  - poetry run reflex run --env prod --frontend-only
serviceAccount:
  create: false
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  hosts:
    - host: test.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific
