image:
  repository: us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-client
  pullPolicy: IfNotPresent
  tag: v281b8fc
env:
  - name: API_URL
    value: https://test-api.gatherplan.site
  - name: BACKEND_URL
    value: http://gatherplan-server.gatherplan-server.svc.cluster.local:8080
command:
  - /bin/bash
args:
  - '-c'
  - poetry run reflex run --env prod --frontend-only
serviceAccount:
  create: false
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: test.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 120

resources:
   requests:
     cpu: 100m
     memory: 512Mi