image:
  repository: us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-server
  pullPolicy: IfNotPresent
  tag: vadc3a02
env:
  - name: JWT_SECRET_KEY
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: JWT_SECRET_KEY
  - name: KAKAO_KEY
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: KAKAO_KEY
  - name: SENDER_EMAIL
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: SENDER_EMAIL
  - name: SENDER_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: SENDER_PASSWORD
  - name: DB_SERVER
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: DB_SERVER
  - name: DB_USER
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: DB_USER
  - name: DB_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
        key: DB_PASSWORD
command:
  - /bin/bash
args:
  - '-c'
  - java -jar app.jar
serviceAccount:
  create: false
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: test-backed.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific
