image:
  repository: us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-server
  pullPolicy: IfNotPresent
  tag: v8fe47c0

env:
  - name: JWT_SECRET_KEY
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
  - name: KAKAO_KEY
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
  - name: SENDER_EMAIL
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
  - name: SENDER_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
  - name: DB_SERVER
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
  - name: DB_USER
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap
  - name: DB_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: gatherplan-configmap

command:
  - /bin/bash
args:
  - '-c'
  - sleep infinity
#  - java -jar app.jar

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: test-backed.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific
