notifications:
  enabled: false

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    hostname: argocd.gatherplan.site
    ingressClassName: nginx


configs:
  cm:
    exec.enabled: true

  rbac:
    policy.csv: |
      g, github, role:admin
    # Policy rules are in the form:
    #  p, subject, resource, action, object, effect
    # Role definitions and bindings are in the form:
    #  g, subject, inherited-subject
    # policy.csv: |
    #   p, role:org-admin, applications, *, */*, allow
    #   p, role:org-admin, clusters, get, *, allow
    #   p, role:org-admin, repositories, *, *, allow
    #   p, role:org-admin, logs, get, *, allow
    #   p, role:org-admin, exec, create, */*, allow
    #   g, your-github-org:your-team, role:org-admin