notifications:
  enabled: false

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    hostname: argocd.gatherplan.site
    ingressClassName: nginx


configs:
  cm:
    exec.enabled: true
