replicaCount: 1
image:
  repository: us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-client
  pullPolicy: IfNotPresent
  tag: vd5ec8a6
env:
  - name: API_URL
    value: http://localhost:8000
  - name: BACKEND_URL
    value: http://gatherplan-server.gatherplan-server.svc.cluster.local:8080
command:
  - /bin/bash
args:
  - '-c'
  - poetry run reflex run --env prod --backend-only
serviceAccount:
  create: false
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 300
readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 120
resources:
  requests:
    cpu: 50m
    memory: 312Mi
