replicaCount: 1
image:
  repository: us-east1-docker.pkg.dev/sharp-voyage-345407/gatherplan/gatherplan-client
  pullPolicy: IfNotPresent
  tag: vadd208e
env:
  - name: API_URL
    value: http://localhost:8000
command:
  - /bin/bash
args:
  - '-c'
  - poetry run reflex run --env prod --backend-only
serviceAccount:
  create: false
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: test-api.gatherplan.site
      paths:
        - path: /
          pathType: ImplementationSpecific
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 120
